$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code
  - name
  - programs

properties:

  availability_mechanism:
    description: >
      Mechanism by which the project will be made avilable.
    type: string

  availability_type:
    description: >
      Is the project open or restricted?
    enum:
      - "Open"
      - "Restricted"

  code:
    description: >
      Unique identifier for the project.
    type: string

  date_collected:
    description: >
      The date or date range in which the project data was collected.
    type: string

  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: >
      UUID for the project.

  intended_release_date:
    description: >
      Tracks a Project's intended release date.
    type: string
    format: date-time

  investigator_affiliation:
    description: >
      The investigator's affiliation with respect to a research institution.
    type: string

  investigator_name:
    description: >
      Name of the principal investigator for the project.
    type: string

  name:
    description: >
      Display name/brief description for the project.
    type: string

  releasable:
    description: >
      A project can only be released by the user when `releasable` is true.
    default: False
    type: boolean

  released:
    description: >
      To release a project is to tell the GDC to include all submitted
      entities in the next GDC index.
    default: False
    type: boolean

  state:
    description: >
      The possible states a project can be in.  All but `open` are
      equivalent to some type of locked state.
    default: open
    enum:
      - "closed"
      - "legacy"
      - "open"
      - "processing"
      - "review"
      - "submitted"

  support_id:
    description: >
      The ID of the source providing support/grant resources.
    type: string

  support_source:
    description: >
      The name of source providing support/grant resources.
    type: string

  this_is_a_test:
    description: >
      this is just a test
    type: string

  type:
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      Indicates that the project is logically part of the indicated project.
